safe: true
source: ./jekyll
destination: ./app
lsi: false
pygments: true
permalink: pretty
url: http://scrumplan.com # http://localhost:8888/ScrumPlan
exclude: ['jekyll','sass','config.rb','humans.txt','robots.txt','LICENSE','README']